import FWCore.ParameterSet.Config as cms

# use ParticleTransformerV2JetTagInfosProducer (include lost track and pixel inputs)
from RecoBTag.ONNXRuntime.boostedJetONNXJetTagsProducer_cfi import boostedJetONNXJetTagsProducer

## GloParT 3 models: ##
# downloaded from https://coli.web.cern.ch/coli/tmp/.230626-003937_partv2_model
# V03pre1: "ak8_MD_inclv8_part_splitreg_extmass_rmhbs_manual.useamp.large_fc2048.gm5.ddp-bs384-lr6e-4.nepoch100.v3fixsplit2", no H->bs class, split-class regression, no pixel inputs

pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTags = boostedJetONNXJetTagsProducer.clone(
    src = 'pfMassDecorrelatedInclParticleTransformerV2TagInfos', # v3 still uses v2 tag infos
    preprocess_json = 'DeepNTuples/Ntupler/data/InclParticleTransformer-MD/ak8/V03pre1/preprocess_corr.json',
    model_path = 'DeepNTuples/Ntupler/data/InclParticleTransformer-MD/ak8/V03pre1/model_embed.onnx',
    flav_names = [
        'probTopbWcs', 'probTopbWqq', 'probTopbWc', 'probTopbWs', 'probTopbWq', 'probTopbWev', 'probTopbWmv', 'probTopbWtauev', 'probTopbWtaumv', 'probTopbWtauhv', 
        'probTopWcs', 'probTopWqq', 'probTopWev', 'probTopWmv', 'probTopWtauev', 'probTopWtaumv', 'probTopWtauhv', 
        'probHbb', 'probHcc', 'probHss', 'probHqq', 'probHbc', 'probHcs', 'probHgg', 'probHee', 'probHmm', 'probHtauhtaue', 'probHtauhtaum', 'probHtauhtauh', # !! temporarily remove Hbs tagger
        'probHWWcscs', 'probHWWcsqq', 'probHWWqqqq', 'probHWWcsc', 'probHWWcss', 'probHWWcsq', 'probHWWqqc', 'probHWWqqs', 'probHWWqqq', 
        'probHWWcsev', 'probHWWqqev', 'probHWWcsmv', 'probHWWqqmv', 'probHWWcstauev', 'probHWWqqtauev', 'probHWWcstaumv', 'probHWWqqtaumv', 'probHWWcstauhv', 'probHWWqqtauhv', 
        'probHWxWxcscs', 'probHWxWxcsqq', 'probHWxWxqqqq', 'probHWxWxcsc', 'probHWxWxcss', 'probHWxWxcsq', 'probHWxWxqqc', 'probHWxWxqqs', 'probHWxWxqqq', 
        'probHWxWxcsev', 'probHWxWxqqev', 'probHWxWxcsmv', 'probHWxWxqqmv', 'probHWxWxcstauev', 'probHWxWxqqtauev', 'probHWxWxcstaumv', 'probHWxWxqqtaumv', 'probHWxWxcstauhv', 'probHWxWxqqtauhv', 
        'probHWxWxStarcscs', 'probHWxWxStarcsqq', 'probHWxWxStarqqqq', 'probHWxWxStarcsc', 'probHWxWxStarcss', 'probHWxWxStarcsq', 'probHWxWxStarqqc', 'probHWxWxStarqqs', 'probHWxWxStarqqq', 
        'probHWxWxStarcsev', 'probHWxWxStarqqev', 'probHWxWxStarcsmv', 'probHWxWxStarqqmv', 'probHWxWxStarcstauev', 'probHWxWxStarqqtauev', 'probHWxWxStarcstaumv', 'probHWxWxStarqqtaumv', 'probHWxWxStarcstauhv', 'probHWxWxStarqqtauhv', 
        'probHZZbbbb', 'probHZZbbcc', 'probHZZbbss', 'probHZZbbqq', 'probHZZcccc', 'probHZZccss', 'probHZZccqq', 'probHZZssss', 'probHZZssqq', 'probHZZqqqq', 'probHZZbbb', 'probHZZbbc', 'probHZZbbs', 'probHZZbbq', 'probHZZccb', 'probHZZccc', 'probHZZccs', 'probHZZccq', 'probHZZssb', 'probHZZssc', 'probHZZsss', 'probHZZssq', 'probHZZqqb', 'probHZZqqc', 'probHZZqqs', 'probHZZqqq', 
        'probHZZbbee', 'probHZZbbmm', 'probHZZbbe', 'probHZZbbm', 'probHZZbee', 'probHZZbmm', 'probHZZbbtauhtaue', 'probHZZbbtauhtaum', 'probHZZbbtauhtauh', 'probHZZbtauhtaue', 'probHZZbtauhtaum', 'probHZZbtauhtauh', 'probHZZccee', 'probHZZccmm', 'probHZZcce', 'probHZZccm', 'probHZZcee', 'probHZZcmm', 'probHZZcctauhtaue', 'probHZZcctauhtaum', 'probHZZcctauhtauh', 'probHZZctauhtaue', 'probHZZctauhtaum', 'probHZZctauhtauh', 'probHZZssee', 'probHZZssmm', 'probHZZsse', 'probHZZssm', 'probHZZsee', 'probHZZsmm', 'probHZZsstauhtaue', 'probHZZsstauhtaum', 'probHZZsstauhtauh', 'probHZZstauhtaue', 'probHZZstauhtaum', 'probHZZstauhtauh', 'probHZZqqee', 'probHZZqqmm', 'probHZZqqe', 'probHZZqqm', 'probHZZqee', 'probHZZqmm', 'probHZZqqtauhtaue', 'probHZZqqtauhtaum', 'probHZZqqtauhtauh', 'probHZZqtauhtaue', 'probHZZqtauhtaum', 'probHZZqtauhtauh', 
        'probHZxZxbbbb', 'probHZxZxbbcc', 'probHZxZxbbss', 'probHZxZxbbqq', 'probHZxZxcccc', 'probHZxZxccss', 'probHZxZxccqq', 'probHZxZxssss', 'probHZxZxssqq', 'probHZxZxqqqq', 'probHZxZxbbb', 'probHZxZxbbc', 'probHZxZxbbs', 'probHZxZxbbq', 'probHZxZxccb', 'probHZxZxccc', 'probHZxZxccs', 'probHZxZxccq', 'probHZxZxssb', 'probHZxZxssc', 'probHZxZxsss', 'probHZxZxssq', 'probHZxZxqqb', 'probHZxZxqqc', 'probHZxZxqqs', 'probHZxZxqqq', 
        'probHZxZxbbee', 'probHZxZxbbmm', 'probHZxZxbbe', 'probHZxZxbbm', 'probHZxZxbee', 'probHZxZxbmm', 'probHZxZxbbtauhtaue', 'probHZxZxbbtauhtaum', 'probHZxZxbbtauhtauh', 'probHZxZxbtauhtaue', 'probHZxZxbtauhtaum', 'probHZxZxbtauhtauh', 'probHZxZxccee', 'probHZxZxccmm', 'probHZxZxcce', 'probHZxZxccm', 'probHZxZxcee', 'probHZxZxcmm', 'probHZxZxcctauhtaue', 'probHZxZxcctauhtaum', 'probHZxZxcctauhtauh', 'probHZxZxctauhtaue', 'probHZxZxctauhtaum', 'probHZxZxctauhtauh', 'probHZxZxssee', 'probHZxZxssmm', 'probHZxZxsse', 'probHZxZxssm', 'probHZxZxsee', 'probHZxZxsmm', 'probHZxZxsstauhtaue', 'probHZxZxsstauhtaum', 'probHZxZxsstauhtauh', 'probHZxZxstauhtaue', 'probHZxZxstauhtaum', 'probHZxZxstauhtauh', 'probHZxZxqqee', 'probHZxZxqqmm', 'probHZxZxqqe', 'probHZxZxqqm', 'probHZxZxqee', 'probHZxZxqmm', 'probHZxZxqqtauhtaue', 'probHZxZxqqtauhtaum', 'probHZxZxqqtauhtauh', 'probHZxZxqtauhtaue', 'probHZxZxqtauhtaum', 'probHZxZxqtauhtauh', 
        'probHZxZxStarbbbb', 'probHZxZxStarbbcc', 'probHZxZxStarbbss', 'probHZxZxStarbbqq', 'probHZxZxStarcccc', 'probHZxZxStarccss', 'probHZxZxStarccqq', 'probHZxZxStarssss', 'probHZxZxStarssqq', 'probHZxZxStarqqqq', 'probHZxZxStarbbb', 'probHZxZxStarbbc', 'probHZxZxStarbbs', 'probHZxZxStarbbq', 'probHZxZxStarccb', 'probHZxZxStarccc', 'probHZxZxStarccs', 'probHZxZxStarccq', 'probHZxZxStarssb', 'probHZxZxStarssc', 'probHZxZxStarsss', 'probHZxZxStarssq', 'probHZxZxStarqqb', 'probHZxZxStarqqc', 'probHZxZxStarqqs', 'probHZxZxStarqqq', 
        'probHZxZxStarbbee', 'probHZxZxStarbbmm', 'probHZxZxStarbbe', 'probHZxZxStarbbm', 'probHZxZxStarbee', 'probHZxZxStarbmm', 'probHZxZxStarbbtauhtaue', 'probHZxZxStarbbtauhtaum', 'probHZxZxStarbbtauhtauh', 'probHZxZxStarbtauhtaue', 'probHZxZxStarbtauhtaum', 'probHZxZxStarbtauhtauh', 'probHZxZxStarccee', 'probHZxZxStarccmm', 'probHZxZxStarcce', 'probHZxZxStarccm', 'probHZxZxStarcee', 'probHZxZxStarcmm', 'probHZxZxStarcctauhtaue', 'probHZxZxStarcctauhtaum', 'probHZxZxStarcctauhtauh', 'probHZxZxStarctauhtaue', 'probHZxZxStarctauhtaum', 'probHZxZxStarctauhtauh', 'probHZxZxStarssee', 'probHZxZxStarssmm', 'probHZxZxStarsse', 'probHZxZxStarssm', 'probHZxZxStarsee', 'probHZxZxStarsmm', 'probHZxZxStarsstauhtaue', 'probHZxZxStarsstauhtaum', 'probHZxZxStarsstauhtauh', 'probHZxZxStarstauhtaue', 'probHZxZxStarstauhtaum', 'probHZxZxStarstauhtauh', 'probHZxZxStarqqee', 'probHZxZxStarqqmm', 'probHZxZxStarqqe', 'probHZxZxStarqqm', 'probHZxZxStarqee', 'probHZxZxStarqmm', 'probHZxZxStarqqtauhtaue', 'probHZxZxStarqqtauhtaum', 'probHZxZxStarqqtauhtauh', 'probHZxZxStarqtauhtaue', 'probHZxZxStarqtauhtaum', 'probHZxZxStarqtauhtauh', 
        'probQCDbb', 'probQCDcc', 'probQCDb', 'probQCDc', 'probQCDothers', 
        'massCorrTopbWcs', 'massCorrTopbWqq', 'massCorrTopbWc', 'massCorrTopbWs', 'massCorrTopbWq', 'massCorrTopbWev', 'massCorrTopbWmv', 'massCorrTopbWtauev', 'massCorrTopbWtaumv', 'massCorrTopbWtauhv', 
        'massCorrTopWcs', 'massCorrTopWqq', 'massCorrTopWev', 'massCorrTopWmv', 'massCorrTopWtauev', 'massCorrTopWtaumv', 'massCorrTopWtauhv', 
        'massCorrHbb', 'massCorrHcc', 'massCorrHss', 'massCorrHqq', 'massCorrHbc', 'massCorrHcs', 'massCorrHgg', 'massCorrHee', 'massCorrHmm', 'massCorrHtauhtaue', 'massCorrHtauhtaum', 'massCorrHtauhtauh', # !! temporarily remove Hbs tagger
        'massCorrHWWcscs', 'massCorrHWWcsqq', 'massCorrHWWqqqq', 'massCorrHWWcsc', 'massCorrHWWcss', 'massCorrHWWcsq', 'massCorrHWWqqc', 'massCorrHWWqqs', 'massCorrHWWqqq', 
        'massCorrHWWcsev', 'massCorrHWWqqev', 'massCorrHWWcsmv', 'massCorrHWWqqmv', 'massCorrHWWcstauev', 'massCorrHWWqqtauev', 'massCorrHWWcstaumv', 'massCorrHWWqqtaumv', 'massCorrHWWcstauhv', 'massCorrHWWqqtauhv', 
        'massCorrHWxWxcscs', 'massCorrHWxWxcsqq', 'massCorrHWxWxqqqq', 'massCorrHWxWxcsc', 'massCorrHWxWxcss', 'massCorrHWxWxcsq', 'massCorrHWxWxqqc', 'massCorrHWxWxqqs', 'massCorrHWxWxqqq', 
        'massCorrHWxWxcsev', 'massCorrHWxWxqqev', 'massCorrHWxWxcsmv', 'massCorrHWxWxqqmv', 'massCorrHWxWxcstauev', 'massCorrHWxWxqqtauev', 'massCorrHWxWxcstaumv', 'massCorrHWxWxqqtaumv', 'massCorrHWxWxcstauhv', 'massCorrHWxWxqqtauhv', 
        'massCorrHWxWxStarcscs', 'massCorrHWxWxStarcsqq', 'massCorrHWxWxStarqqqq', 'massCorrHWxWxStarcsc', 'massCorrHWxWxStarcss', 'massCorrHWxWxStarcsq', 'massCorrHWxWxStarqqc', 'massCorrHWxWxStarqqs', 'massCorrHWxWxStarqqq', 
        'massCorrHWxWxStarcsev', 'massCorrHWxWxStarqqev', 'massCorrHWxWxStarcsmv', 'massCorrHWxWxStarqqmv', 'massCorrHWxWxStarcstauev', 'massCorrHWxWxStarqqtauev', 'massCorrHWxWxStarcstaumv', 'massCorrHWxWxStarqqtaumv', 'massCorrHWxWxStarcstauhv', 'massCorrHWxWxStarqqtauhv', 
        'massCorrHZZbbbb', 'massCorrHZZbbcc', 'massCorrHZZbbss', 'massCorrHZZbbqq', 'massCorrHZZcccc', 'massCorrHZZccss', 'massCorrHZZccqq', 'massCorrHZZssss', 'massCorrHZZssqq', 'massCorrHZZqqqq', 'massCorrHZZbbb', 'massCorrHZZbbc', 'massCorrHZZbbs', 'massCorrHZZbbq', 'massCorrHZZccb', 'massCorrHZZccc', 'massCorrHZZccs', 'massCorrHZZccq', 'massCorrHZZssb', 'massCorrHZZssc', 'massCorrHZZsss', 'massCorrHZZssq', 'massCorrHZZqqb', 'massCorrHZZqqc', 'massCorrHZZqqs', 'massCorrHZZqqq', 
        'massCorrHZZbbee', 'massCorrHZZbbmm', 'massCorrHZZbbe', 'massCorrHZZbbm', 'massCorrHZZbee', 'massCorrHZZbmm', 'massCorrHZZbbtauhtaue', 'massCorrHZZbbtauhtaum', 'massCorrHZZbbtauhtauh', 'massCorrHZZbtauhtaue', 'massCorrHZZbtauhtaum', 'massCorrHZZbtauhtauh', 'massCorrHZZccee', 'massCorrHZZccmm', 'massCorrHZZcce', 'massCorrHZZccm', 'massCorrHZZcee', 'massCorrHZZcmm', 'massCorrHZZcctauhtaue', 'massCorrHZZcctauhtaum', 'massCorrHZZcctauhtauh', 'massCorrHZZctauhtaue', 'massCorrHZZctauhtaum', 'massCorrHZZctauhtauh', 'massCorrHZZssee', 'massCorrHZZssmm', 'massCorrHZZsse', 'massCorrHZZssm', 'massCorrHZZsee', 'massCorrHZZsmm', 'massCorrHZZsstauhtaue', 'massCorrHZZsstauhtaum', 'massCorrHZZsstauhtauh', 'massCorrHZZstauhtaue', 'massCorrHZZstauhtaum', 'massCorrHZZstauhtauh', 'massCorrHZZqqee', 'massCorrHZZqqmm', 'massCorrHZZqqe', 'massCorrHZZqqm', 'massCorrHZZqee', 'massCorrHZZqmm', 'massCorrHZZqqtauhtaue', 'massCorrHZZqqtauhtaum', 'massCorrHZZqqtauhtauh', 'massCorrHZZqtauhtaue', 'massCorrHZZqtauhtaum', 'massCorrHZZqtauhtauh', 
        'massCorrHZxZxbbbb', 'massCorrHZxZxbbcc', 'massCorrHZxZxbbss', 'massCorrHZxZxbbqq', 'massCorrHZxZxcccc', 'massCorrHZxZxccss', 'massCorrHZxZxccqq', 'massCorrHZxZxssss', 'massCorrHZxZxssqq', 'massCorrHZxZxqqqq', 'massCorrHZxZxbbb', 'massCorrHZxZxbbc', 'massCorrHZxZxbbs', 'massCorrHZxZxbbq', 'massCorrHZxZxccb', 'massCorrHZxZxccc', 'massCorrHZxZxccs', 'massCorrHZxZxccq', 'massCorrHZxZxssb', 'massCorrHZxZxssc', 'massCorrHZxZxsss', 'massCorrHZxZxssq', 'massCorrHZxZxqqb', 'massCorrHZxZxqqc', 'massCorrHZxZxqqs', 'massCorrHZxZxqqq', 
        'massCorrHZxZxbbee', 'massCorrHZxZxbbmm', 'massCorrHZxZxbbe', 'massCorrHZxZxbbm', 'massCorrHZxZxbee', 'massCorrHZxZxbmm', 'massCorrHZxZxbbtauhtaue', 'massCorrHZxZxbbtauhtaum', 'massCorrHZxZxbbtauhtauh', 'massCorrHZxZxbtauhtaue', 'massCorrHZxZxbtauhtaum', 'massCorrHZxZxbtauhtauh', 'massCorrHZxZxccee', 'massCorrHZxZxccmm', 'massCorrHZxZxcce', 'massCorrHZxZxccm', 'massCorrHZxZxcee', 'massCorrHZxZxcmm', 'massCorrHZxZxcctauhtaue', 'massCorrHZxZxcctauhtaum', 'massCorrHZxZxcctauhtauh', 'massCorrHZxZxctauhtaue', 'massCorrHZxZxctauhtaum', 'massCorrHZxZxctauhtauh', 'massCorrHZxZxssee', 'massCorrHZxZxssmm', 'massCorrHZxZxsse', 'massCorrHZxZxssm', 'massCorrHZxZxsee', 'massCorrHZxZxsmm', 'massCorrHZxZxsstauhtaue', 'massCorrHZxZxsstauhtaum', 'massCorrHZxZxsstauhtauh', 'massCorrHZxZxstauhtaue', 'massCorrHZxZxstauhtaum', 'massCorrHZxZxstauhtauh', 'massCorrHZxZxqqee', 'massCorrHZxZxqqmm', 'massCorrHZxZxqqe', 'massCorrHZxZxqqm', 'massCorrHZxZxqee', 'massCorrHZxZxqmm', 'massCorrHZxZxqqtauhtaue', 'massCorrHZxZxqqtauhtaum', 'massCorrHZxZxqqtauhtauh', 'massCorrHZxZxqtauhtaue', 'massCorrHZxZxqtauhtaum', 'massCorrHZxZxqtauhtauh', 
        'massCorrHZxZxStarbbbb', 'massCorrHZxZxStarbbcc', 'massCorrHZxZxStarbbss', 'massCorrHZxZxStarbbqq', 'massCorrHZxZxStarcccc', 'massCorrHZxZxStarccss', 'massCorrHZxZxStarccqq', 'massCorrHZxZxStarssss', 'massCorrHZxZxStarssqq', 'massCorrHZxZxStarqqqq', 'massCorrHZxZxStarbbb', 'massCorrHZxZxStarbbc', 'massCorrHZxZxStarbbs', 'massCorrHZxZxStarbbq', 'massCorrHZxZxStarccb', 'massCorrHZxZxStarccc', 'massCorrHZxZxStarccs', 'massCorrHZxZxStarccq', 'massCorrHZxZxStarssb', 'massCorrHZxZxStarssc', 'massCorrHZxZxStarsss', 'massCorrHZxZxStarssq', 'massCorrHZxZxStarqqb', 'massCorrHZxZxStarqqc', 'massCorrHZxZxStarqqs', 'massCorrHZxZxStarqqq', 
        'massCorrHZxZxStarbbee', 'massCorrHZxZxStarbbmm', 'massCorrHZxZxStarbbe', 'massCorrHZxZxStarbbm', 'massCorrHZxZxStarbee', 'massCorrHZxZxStarbmm', 'massCorrHZxZxStarbbtauhtaue', 'massCorrHZxZxStarbbtauhtaum', 'massCorrHZxZxStarbbtauhtauh', 'massCorrHZxZxStarbtauhtaue', 'massCorrHZxZxStarbtauhtaum', 'massCorrHZxZxStarbtauhtauh', 'massCorrHZxZxStarccee', 'massCorrHZxZxStarccmm', 'massCorrHZxZxStarcce', 'massCorrHZxZxStarccm', 'massCorrHZxZxStarcee', 'massCorrHZxZxStarcmm', 'massCorrHZxZxStarcctauhtaue', 'massCorrHZxZxStarcctauhtaum', 'massCorrHZxZxStarcctauhtauh', 'massCorrHZxZxStarctauhtaue', 'massCorrHZxZxStarctauhtaum', 'massCorrHZxZxStarctauhtauh', 'massCorrHZxZxStarssee', 'massCorrHZxZxStarssmm', 'massCorrHZxZxStarsse', 'massCorrHZxZxStarssm', 'massCorrHZxZxStarsee', 'massCorrHZxZxStarsmm', 'massCorrHZxZxStarsstauhtaue', 'massCorrHZxZxStarsstauhtaum', 'massCorrHZxZxStarsstauhtauh', 'massCorrHZxZxStarstauhtaue', 'massCorrHZxZxStarstauhtaum', 'massCorrHZxZxStarstauhtauh', 'massCorrHZxZxStarqqee', 'massCorrHZxZxStarqqmm', 'massCorrHZxZxStarqqe', 'massCorrHZxZxStarqqm', 'massCorrHZxZxStarqee', 'massCorrHZxZxStarqmm', 'massCorrHZxZxStarqqtauhtaue', 'massCorrHZxZxStarqqtauhtaum', 'massCorrHZxZxStarqqtauhtauh', 'massCorrHZxZxStarqtauhtaue', 'massCorrHZxZxStarqtauhtaum', 'massCorrHZxZxStarqtauhtauh', 
        'massCorrQCDbb', 'massCorrQCDcc', 'massCorrQCDb', 'massCorrQCDc', 'massCorrQCDothers',
    ] + ['hidNeuron%s' % str(idx).zfill(3) for idx in range(256)],
    debugMode = False,
)

# declare all the discriminators
# probs
_pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbs = ['pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTags:' + flav_name
                                 for flav_name in pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTags.flav_names]
_pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbsRawScores = [disc for disc in _pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbs if 'hidNeuron' not in disc]
_pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbsHidNeurons = [disc for disc in _pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbs if 'hidNeuron' in disc]

# meta-taggers
_pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsMetaDiscrs = []
_pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsAll = _pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsProbs + _pfMassDecorrelatedInclParticleTransformerV3HidLayerJetTagsMetaDiscrs
